### ISSUE TITLE
I would suggest that "autoscan" be added to the apps to be installed

### ISSUE THREAD

**Issue by CLHatch** [GhostWriters/DockSTARTer#1026]
# Feature request

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like the autoscan container added to the list of installable apps.  Obviously it can be done with an override, but I think this is an app that should be included in the "standard" app list.

**Describe alternatives you've considered**
I've been using the horjulf/plex_autoscan container, which is Plex with the old version of plex_autoscan built in (it's based on the LinuxServer Plex container); hotio has a tag for their Plex container that does the same.  However, "plex_autoscan" is now depreciated, they've now re-written it in Go, and named it "autoscan".

**Additional context**
hotio's Docker image is here: https://hub.docker.com/r/hotio/autoscan
autoscan's github page is here: https://github.com/Cloudbox/autoscan

**Comment by angrycuban13** [comment]
It is still in Alpha, so we should hold off on adding it until it has been completed.

**Comment by CLHatch** [comment]
> It is still in Alpha, so we should hold off on adding it until it has been completed.

Yeah, makes sense, or you may end up playing "catch up" in DS, with possibly changing environment variables, etc.

**Comment by angrycuban13** [comment]
I have reached out to them to help with the technical documentation so maybe I can provide a timeline if they accept my request

**Comment by nemchik** [comment]
I've spoken to the dev and it's still not quite ready. It's a great app and I'm using it personally, but I'll wait for the dev to give the green light.

**Comment by nemchik** [comment]
For now here's my override
```yaml

  autoscan:
    image: cloudb0x/autoscan
    hostname: ${DOCKERHOSTNAME}
    ports:
      - 3030:3030
    container_name: autoscan
    environment:
      - AUTOSCAN_VERBOSITY=0
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt:/mnt:ro
      - /opt/sa:/opt/sa
      - ${DOCKERCONFDIR}/autoscan:/config
      - ${DOCKERSHAREDDIR}:/shared
```
You may need different volumes.
