### ISSUE TITLE
Apps: FlareSolverr / wallabag

### ISSUE THREAD

**Issue by spider1163** [GhostWriters/DockSTARTer#1234]
Hello,

I wanted to share apps I am using :

Some indexers are protected by CloudFlare or similar services and Jackett is not able to solve the challenges. 
For these cases, FlareSolverr has been integrated into Jackett. 
This service is in charge of solving the challenges and configuring Jackett with the necessary cookies. 
Setting up this service is optional, most indexers don't need it.
- Install FlareSolverr service
- Configure FlareSolverr API URL in Jackett. For example: http://flaresolverr:8191

https://github.com/FlareSolverr/FlareSolverr
https://hub.docker.com/r/flaresolverr/flaresolverr

---

wallabag is a self hostable application for saving web pages (= alternative to Pocket)
Unlike other services, wallabag is free (as in freedom) and open source

https://github.com/wallabag/docker
https://hub.docker.com/r/wallabag/wallabag

**Comment by spider1163** [comment]
Note : I use ugeek/wallabag:arm-2.4 for Raspberry Pi

https://hub.docker.com/layers/ugeek/wallabag/arm-2.4/images/sha256-40f4ded6c1be97c3f9c52b0fda1787adbc147cfa44c008d358c38d2af34b45af?context=explore

**Comment by angrycuban13** [comment]
@spider1163 thanks for providing the necessary links for these applications. Two quick things, we have templates that are specific, be sure to use them :) 

As I like to reference issues in my PRs to automatically close them, do you mind creating a separate issue for each application in the future? Thanks.

I will get started on creating a PR to include these applications

**Comment by angrycuban13** [comment]
@spider1163 can you please provide me with a copy of your compose and the output of
```bash
ls -lah /path/to/wallabag/images
```
Right now, anytime I test it locally it looks like this
![wallabag](https://sharex.angrycuban.xyz/XExe1/WihOnUPu19.png/raw)

This is what I have as my compose
```yml
  wallabag:
    container_name: wallabag
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=mariadb
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=wallapass
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__DOMAIN_NAME=https://wallabag.domain.com
      - SYMFONY__ENV__SERVER_NAME="Your wallabag instance"
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/wallabag/images:/var/www/wallabag/web/assets/images
      - ${DOCKERSTORAGEDIR}:/storage
    ports:
      - 9999:80
    image: wallabag/wallabag
```
