### ISSUE TITLE
Application request: Nginx proxy manager

### ISSUE THREAD

**Issue by 1985kasper** [GhostWriters/DockSTARTer#1280]
Instead or in addition to SWAG the nginx proxy manager looks like a pretty good option to manage secure accessing apps from the outside. 

Would love to see this added to dockstarter

**Comment by Borkuz** [comment]
just add this to your docker-compose.override.yaml:


```
 proxymanager:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxymanager
    ports:
      - 80:80
      - 81:81
      - 443:443
    environment:
      DB_SQLITE_FILE: /data/database.sqlite
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ${DOCKERCONFDIR}/proxymanager/data:/data
      - ${DOCKERCONFDIR}/proxymanager/letsencrypt:/etc/letsencrypt
```
