### ISSUE TITLE
[Application Request] Potentially replacing the vsftpd image by sftpgo

### ISSUE THREAD

**Issue by ltctceplrm** [GhostWriters/DockSTARTer#1297]
# Name of the application
sftpgo
## GitHub
https://github.com/drakkan/sftpgo
## Docker Hub/GitHub Registry
https://hub.docker.com/r/drakkan/sftpgo
### Additional context
I've posted in the discord about my problems with the vsftpd image but I'll do a quick recap here: The current image overwrites the virtual users file each time the container is recreated so you can only have the admin user.
I tried to find an alternative program and found sftpgo, here's my docker compose for it: 

```
sftpgo:
    image: "drakkan/sftpgo:latest"
    hostname: ${DOCKERHOSTNAME}
    restart: unless-stopped
    ports:
      - "2022:2022"
      - "2021:2021"
      - "8090:8080"
    container_name: sftpgo
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    environment:
      - SFTPGO_HTTPD__BINDINGS__0__PORT=8080
      - SFTPGO_FTPD__BINDINGS__0__PORT=2021
      - PGID=${PGID}
      - PUID=${PUID}
    volumes:
      - ${DOCKERCONFDIR}/sftpgo:/var/lib/sftpgo
      - ${DOCKERCONFDIR}/sftpgo/sftp_auth:/etc/sftpgo/sftp_auth
      - ${DOCKERSTORAGEDIR}:/storage
      - /mnt/sftpgo:/srv/sftpgo
      - /etc/localtime:/etc/localtime:ro
```

The only problem I had was that the image doesn't chown the config folder in appdata so it's owned by root rather than my PID of 1000 so sftpgo couldn’t write anything in its data folder. After I chowned it myself it worked fine.

You can add users easily using the web interface, change their permissions or add data quotas, use virtual folders, etc.
I needed sftp and ftp so I added `SFTPGO_FTPD__BINDINGS__0__PORT=2021` to enable ftp but you could add an dockstarter variable where you ask the user which port to use for ftp and to use 0 to disable it.

Some [screenshots](https://perfecto25.medium.com/goftp-the-vsftpd-on-steroids-19b2d3c5dde8) present here.
And here are the [all variables](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md).
