### ISSUE TITLE
[BUG] Watchtower constantly restarting

### ISSUE THREAD

**Issue by setchy** [GhostWriters/DockSTARTer#1556]
# Bug report

**Describe the bug**
The watchtower app, when configured via DockStarter is in a constant restart loop.

**To Reproduce**

- Install `watchtower` via `ds`
- Monitor via docker cli or Portainer

**Expected behavior**
Watchtower does not constantly restart

**Screenshots**

**System**
(please complete the following information):

- OS: Debian
- Version Bullseye
**Additional context**

**Comment by setchy** [comment]
However, using a simpler setup manually it works as expected
```
services:
  watchtower: 
    image: containrrr/watchtower:latest 
    container_name: watchtower 
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock 
 ```
