### ISSUE TITLE
[BUG] Huginn default settings broken(?)

### ISSUE THREAD

**Issue by brickfrog** [GhostWriters/DockSTARTer#1589]
# Bug report

**Describe the bug**
I believe the base variables with Huginn no longer work. Running with defaults doesn't expose the interface compared to running a base "docker run -it -p 3000:3000 huginn/huginn" / dockstarter with deleted variables. Thought it might confuse new(er) users since unless you completely override, it causes the service to not be exposed.

**To Reproduce**

Fresh addition of Huginn -> visit localhost:3000

**Expected behavior**

The interface to be available similar to running the temporary docker command / using blank env in compose

**System**
(please complete the following information):

- Ubuntu 22.04.1 LTS

**Additional context**

I was able to get it working by using the override file and removing it from the app list so it wouldn't interfere, copied the provided compose env over deleted  the base env variables so the container defaults would run and everything seems to work fine, unsure if mariadb is at fault since mysql is container default:

```
name: compose
services:
  huginn:
    container_name: huginn
    hostname: DockSTARTer
    image: huginn/huginn
    networks:
      default: null
    ports:
    - mode: ingress
      target: 3000
      published: "3000"
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
      bind:
        create_host_path: true
    - type: bind
      source: /mnt/media
      target: /storage
      bind:
        create_host_path: true
~                                                                                      
```
