### ISSUE TITLE
[Application Request] wg-easy

### ISSUE THREAD

**Issue by dylanmtaylor** [GhostWriters/DockSTARTer#1661]
# Name of the application

wg-easy

## GitHub

https://github.com/wg-easy/wg-easy

## Docker Hub/GitHub Registry

https://hub.docker.com/r/weejewel/wg-easy

### Additional context

wg-easy is almost certainly a better Wireguard management experience than the only currently supported Wireguard container for most people.

**Comment by dylanmtaylor** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

This is still desired.

**Comment by spencebah** [comment]
This is still wanted.

**Comment by bababash** [comment]
I have got it working using `docker-compose.override.yml`

References used to generate this: 

- [https://github.com/wg-easy/wg-easy](https://github.com/wg-easy/wg-easy)
- [https://dockstarter.com/overrides/introduction/#full-app-override-example](https://dockstarter.com/overrides/introduction/#full-app-override-example)

```
services:
  wg-easy:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    container_name: wg-easy
    environment:
      - LANG=en
      - WG_HOST=<🚨YOUR_SERVER_IP>
      - PASSWORD_HASH=<🚨YOUR_ADMIN_PASSWORD_HASH>
      - PORT=51821
      - WG_PORT=51820
      - PGID=${PGID}
      - PUID=${PUID}
      - WG_ALLOWED_IPS=<🚨YOUR_SERVER_SUBNET e.g. 192.168.1./24>
      - WG_DEFAULT_DNS=<🚨YOUR_ROUTER_IP>
      - UI_CHART_TYPE=3
      - UI_TRAFFIC_STATS=true
    image: ghcr.io/wg-easy/wg-easy
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    volumes:
      - ${DOCKERCONFDIR}/wg-easy:/etc/wireguard
```


The following arguments were optional, I needed to add them to get it working for my setup
```
      - WG_ALLOWED_IPS
      - WG_DEFAULT_DNS
      - UI_CHART_TYPE
      - UI_TRAFFIC_STATS
```

I hope to have enough time to add this as a pull request. It's pretty good. Way easier than command line
