### ISSUE TITLE
[BUG] Rootless docker requires changes to /var/run/docker.sock binding

### ISSUE THREAD

**Issue by VaporwareII** [GhostWriters/DockSTARTer#1664]
# Bug report

**Describe the bug**
Rootless docker works aside from things that rely on the docker.sock
-v "/var/run/docker.sock:/var/run/docker.sock"

it can be fixed with the replacement (assuming the user is `#1000`)
/run/user/1000/docker.sock
-v "/run/user/1000/docker.sock:/var/run/docker.sock"

or 
    volumes:
    - type: bind
      source: /run/user/1000/docker.sock
      target: /var/run/docker.sock
      bind:
        create_host_path: true

**To Reproduce**
install Docker rootless
spin up a portainer instance.  the Primary environment is down
if I edit the portainer.yml to 
```
services:
  portainer:
    command: "-H unix:///var/run/docker.sock"
    container_name: portainer
    environment:
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: ${PORTAINER_RESTART}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/user/1000/docker.sock:/var/run/docker.sock
      - ${DOCKERCONFDIR}/portainer:/data
      - ${DOCKERSTORAGEDIR}:/storage
```
then it works fine.

**Expected behavior**
Docker Rootless would act like root

**Screenshots**
unmodified:
![image](https://github.com/GhostWriters/DockSTARTer/assets/12813849/6046c5e8-1cae-4331-bc46-83335d6921bf)
modified:
![image](https://github.com/GhostWriters/DockSTARTer/assets/12813849/7f019f11-59e2-4e1a-b1b5-565132b3f028)

**System**
(please complete the following information):

- OS: Armbian
- Version Linux 6.1.21-v8+ `#1642` SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

**Additional context**
it's relatively easy to fix but I'm not sure how to properly override this, so I keep getting stepped on by re-running creation.
This may require a new global variable to identify if the user is rootless and if so what their UID is.
