### ISSUE TITLE
Wireguard VPN server

### ISSUE THREAD

**Issue by gearbread** [GhostWriters/DockSTARTer#431]
Soon Wireguard will be getting Kernel support. Considering the elegance and simplicity of Wireguard (it is less than 5k lines of code) it would be nice to have as an alternative to OpenVPN.

**Comment by nemchik** [comment]
If there is a docker container that has Wireguard in it I wouldn't mind adding it to the project. Do you have any links or other information?

FYI some other criteria would be:
- There must be a stable release
- The app itself must be actively maintained
- The image on Docker Hub must be actively maintained

**Comment by Antexa** [comment]
https://hub.docker.com/r/linuxserver/wireguard

Are you planning to consider this ?

**Comment by nemchik** [comment]
Yes. I've been keeping my eye on it. Forgot about this thread.

**Comment by jodfie** [comment]
#951 i will be making at least a override page for it.

**Comment by Antexa** [comment]
Hi @nemchik, Any ETA on getting support of Wireguard ? In a meantime, I will check the override way you provided to set this up :)

**Comment by angrycuban13** [comment]
@Antexa 
> If there is a docker container that has Wireguard in it I wouldn't mind adding it to the project. Do you have any links or other information?
> 
> 
> 
> FYI some other criteria would be:
> 
> - There must be a stable release
> 
> - The app itself must be actively maintained
> 
> - The image on Docker Hub must be actively maintained

**Comment by Antexa** [comment]
@angrycuban13 : https://hub.docker.com/r/linuxserver/wireguard

**Comment by angrycuban13** [comment]
PR should be coming in soon for this.

**Comment by angrycuban13** [comment]
@Antexa please run `ds -u origin/wireguard` and test it for me.

**Comment by Antexa** [comment]
Hi @angrycuban13, no issue so far

This could be awesome if a default setup could come out of the box with some default value:

```
services:
  wireguard:
    labels:
      com.dockstarter.appinfo.deprecated: "false"
      com.dockstarter.appinfo.description: "WireGuard is an extremely simple yet fast and modern VPN that utilizes state-of-the-art cryptography."
      com.dockstarter.appinfo.nicename: "Wireguard"
      com.dockstarter.appvars.wireguard_enabled: "false"
      com.dockstarter.appvars.wireguard_network_mode: ""
      com.dockstarter.appvars.wireguard_port_51820: "51820"
      com.dockstarter.appvars.wireguard_server_url: ""
      com.dockstarter.appvars.wireguard_server_port: "51820"
      com.dockstarter.appvars.wireguard_peers: "1"
      com.dockstarter.appvars.wireguard_peer_dns: "auto"
      com.dockstarter.appvars.wireguard_internal_subnet: "10.13.13.0/24"
      com.dockstarter.appvars.wireguard_allowed_ips: "0.0.0.0/0"
```
"com.dockstarter.appvars.wireguard_server_url" is there a way to get the public ip ?
