### ISSUE TITLE
Samba Config missing 137:137/udp and 138:138/udp ports

### ISSUE THREAD

**Issue by Tharic99** [GhostWriters/DockSTARTer#498]
**Describe the bug**
Out of box default install of DockSTARTer Samba docker is missing the ports needed to browse the config from a network share. Per the Samba docker wiki docks at https://github.com/dperson/samba/wiki the following line should be added to the config -

-p 137:137/udp -p 138:138/udp [optional] port bindings for 'nmbd' daemon to advertise the shares

This allows a machine to browse the share name correctly.

**To Reproduce**
Install Samba docker fresh without adjusting override config.

**Expected behavior**
Samba docker default install includes 137:137/udp and 138:138/udp by default so Samba shares are visible.

Snippet of docker-compose.override.yml file needed.

```

  samba:
    container_name: samba
    environment:
      - TZ=${TZ}
    image: dperson/samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    networks:
      - default
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ${MEDIADIR_MOVIES}:/movies
      - ${MEDIADIR_MUSIC}:/music
      - ${MEDIADIR_TV}:/tv
      - ${MEDIADIR_BOOKS}:/books
      - ${MEDIADIR_COMICS}:/comics
      - ${DOCKERCONFDIR}:/dockerconfig
    command: '-s "tv;/tv" -s "movies;/movies" -s "books;/books" -s "comics;/comics" -s "Docker Config;/dockerconfig"'

```
