### ISSUE TITLE
Feature: Health check

### ISSUE THREAD

**Issue by kiwijunglist** [GhostWriters/DockSTARTer#578]
Example for jackett compose.

```
services:
  jackett:
    # usual docker compose image / environment / ports / etc
    healthcheck:
      test: curl --fail -s http://localhost:9117/UI/Dashboard || exit 1
      interval: 90s
      timeout: 15s
      retries: 3
```

There is also a container that can be set to restart other unhealthy containers.

https://hub.docker.com/r/willfarrell/autoheal/

```
  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
