### ISSUE TITLE
[Feature Request] Zoneminder would be a good addition

### ISSUE THREAD

**Issue by htpcBeginner** [GhostWriters/DockSTARTer#610]

**Comment by nemchik** [comment]
It seems like I've seen a bunch of people using this, so I would agree it can be added to the templates.

Here is an override I made that you can use in the meantime while I prep the files to be added to the repo:

```yaml
version: "3.4"
services:

  zoneminder:
    image: quantumobject/docker-zoneminder
    container_name: zoneminder
    hostname: ${DOCKERHOSTNAME}
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT=root
      - TZ=${TZ}
      - ZM_DB_HOST=mariadb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/zoneminder/backups:/var/backups
      - /mnt/zoneminder/images:/var/cache/zoneminder
      - ${DOCKERSHAREDDIR}:/shared
    ports:
      - "8000:80"
```
