### ISSUE TITLE
Adguard would be good next to pihole

### ISSUE THREAD

**Issue by noorbertt** [GhostWriters/DockSTARTer#622]
https://hub.docker.com/r/adguard/adguardhome

**Comment by noorbertt** [comment]
Dear, 
Could you help me a bit please?
I was try to setup adguard with compose file, but somethong wrong:

adguard:
    image: adguard/adguardhome
    container_name: adguard
    hostname: ${DOCKERHOSTNAME}
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    volumes:
       - /home/norbert/./docker/config/adguardhome/work:/opt/adguardhome/work
       - /home/norbert/./docker/config/adguardhome/conf:/opt/adguardhome/conf
    ports:
      - "3000:3000"

What am I missing here?

**Comment by nemchik** [comment]
It looks like you have everything, but I can't tell if the indentation is correct. You can use markdown code blocks like this

\`\`\`
multi
line
code
\`\`\`

**Comment by noorbertt** [comment]
unfortunately it's not working for me. I will wait, maybe when you guys have a time.. :)

**Comment by nemchik** [comment]
Now that I'm in front of a PC I was able to review what you posted a little more and see the indentation by editing your comment (didn't actually edit it, just pressed the edit button to see what you had). Please use proper code blocks in the future as it won't require me to use the edit comment feature to see your indentation.

you have:
```yaml
adguard:
    image: adguard/adguardhome
    container_name: adguard
    hostname: ${DOCKERHOSTNAME}
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    volumes:
       - /home/norbert/./docker/config/adguardhome/work:/opt/adguardhome/work
       - /home/norbert/./docker/config/adguardhome/conf:/opt/adguardhome/conf
    ports:
      - "3000:3000"
```

which looks to be incorrect with the volumes. I would recommend:
```yaml
adguard:
    image: adguard/adguardhome
    container_name: adguard
    hostname: ${DOCKERHOSTNAME}
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    volumes:
       - /home/norbert/.docker/config/adguardhome/work:/opt/adguardhome/work
       - /home/norbert/.docker/config/adguardhome/conf:/opt/adguardhome/conf
    ports:
      - "3000:3000"
```
Or use the DOCKERCONFDIR variable like you see in the templates in this repo.
