### ISSUE TITLE
VPN

### ISSUE THREAD

**Issue by ftmflea** [GhostWriters/DockSTARTer#71]
#### DelugeVPN
- [x] Test DelugeVPN
- [x] Make any changes required to get it DelugeVPN working
- [x] Figure out what's resetting settings on recreation
- [x] DelugeVPN fully ready to ship (check above boxes above first)
#### rTorrentVPN
- [x] Start work on rTorrentVPN
- [ ] Test rTorrentVPN
- [ ] Make any changes required to get it rTorrentVPN working
- [ ] rTorrentVPN fully ready to ship (check above boxes above first)
#### SABNZBdVPN
- [x] Test SABNZBdVPN
- [x] Make any changes required to get it SABNZBdVPN working
- [ ] Double check SABNZBdVPN running through VPN
- [ ] SABNZBdVPN fully ready to ship (check above boxes above first)
#### TransmissionVPN
- [x] Test TransmissionVPN
- [x] Make any changes required to get it TransmissionVPN working
- [x] TransmissionVPN fully ready to ship (check above boxes above first)

***

Current notes:

**DelugeVPN:**
I think my install got corrupted somehow.  I reinstalled it and it's working now.

**rTorrentVPN:**
Unable to get running so far.

**SABNZBdVPN:**
Runs. Need to check to see if running through VPN.  Ideas?

**TransmissionVPN:**
This one works.  No problems.

**Comment by nemchik** [comment]
If you leave `OPENVPN_CONFIG` blank does it work?

P.S. I'm about to push a new commit to the branch so if you wouldn't mind updating your local copy (`git pull` should work) and testing again with the new changes that would be awesome!

**Comment by ftmflea** [comment]
Yeah, so transmission-vpn will use a default config with PIA (not sure about others) if it can't find the config file.  I think you would need to point to it in the volumes.

**Comment by ftmflea** [comment]
This works, just need to change: image: haugene/transmission-openvpn
 ```
 transmissionvpn:
    container_name: transmissionvpn
    image: haugene/transmission-openvpn
    cap_add:
    - NET_ADMIN
    devices:
    - /dev/net/tun
    restart: always
    ports:
    - ${TRANSMISSIONVPN_PORT_9091}:9091
    dns:
    - 1.1.1.1
    - 1.0.0.1
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${DOCKERCONFDIR}/transmissionvpn:/config
    - ${DOWNLOADSDIR}:/downloads
    environment:
    - LOCAL_NETWORK=${LAN_NETWORK}
    - OPENVPN_OPTS=${VPN_OPTIONS}
    - OPENVPN_PASSWORD=${VPN_PASS}
    - OPENVPN_PROVIDER=${VPN_PROV}
    - OPENVPN_USERNAME=${VPN_USER}
    - PGID=${PGID}
    - PUID=${PUID}
    - TRANSMISSION_DOWNLOAD_DIR=/downloads/completed
    - TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete
    - TRANSMISSION_WATCH_DIR=/downloads/watch
    - TZ=${TZ}
```

**Comment by nemchik** [comment]
So the only thing you changed was the image? I wonder what's wrong with the Alpine one. That's fine though we can stick with the regular one.

**Comment by ftmflea** [comment]
it kept looking for tinyproxy.sh or something.

Got DelugeVPN working with this:

```
  delugevpn:
    cap_add:
    - NET_ADMIN
    container_name: delugevpn
    image: binhex/arch-delugevpn
    environment:
    - LAN_NETWORK=${LAN_NETWORK}
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    - VPN_ENABLED=${VPN_ENABLE}
    - VPN_PASS=${VPN_PASS}
    - VPN_PROV=${VPN_PROV}
    - VPN_USER=${VPN_USER}
    - NAME_SERVERS=${NAME_SERVERS}
    ports:
    - ${DELUGEVPN_PORT_58846}:58846
    - ${DELUGEVPN_PORT_58946}:58946
    - ${DELUGEVPN_PORT_8112}:8112
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${DOCKERCONFDIR}/delugevpn:/config
    - ${DOWNLOADSDIR}:/downloads
```
