### ISSUE TITLE
docker-compose.override.yml isn't overriding values

### ISSUE THREAD

**Issue by cdashrowe** [GhostWriters/DockSTARTer#756]
**Describe the bug**
Trying to override calibreweb to include `DOCKER_MODS=linuxserver/calibre-web:calibre` but the override isn't being merged.

**To Reproduce**
Create docker-compose.override.yml in ~/.docker/compose/ and add

```
version: "3.4"
services:
  calibreweb:
    environment:
    - DOCKER_MODS=linuxserver/calibre-web:calibre
```

**Expected behavior**
The config is merged.

**System (please complete the following information):**
Ubuntu Server 18.04
