### ISSUE TITLE
The YAML formatted files are not compliant to the spec

### ISSUE THREAD

**Issue by LandonStewart** [GhostWriters/DockSTARTer#786]
**Describe the bug**
The format of the YAML files are not compliant with the spec.

**To Reproduce**

1. Look at a yml file like .docker/compose/docker-compose.yml
2. See that it's missing the '---' at the start of the file
3. See that the indentation is wrong for lists

**Expected behavior**
This:
```
services:
  homeassistant:
    container_name: homeassistant
    environment:
    - TZ=${TZ}
    hostname: ${DOCKERHOSTNAME}
    image: homeassistant/raspberrypi3-homeassistant
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
    - ${HOMEASSISTANT_PORT_8123}:8123
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${DOCKERCONFDIR}/homeassistant:/config
    - ${DOCKERSHAREDDIR}:/shared
```

Should be this:
```
---
services:
  homeassistant:
    container_name: homeassistant
    environment:
      - TZ=${TZ}
    hostname: ${DOCKERHOSTNAME}
    image: homeassistant/raspberrypi3-homeassistant
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - ${HOMEASSISTANT_PORT_8123}:8123
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/homeassistant:/config
      - ${DOCKERSHAREDDIR}:/shared
```
**Screenshots**

- None

**System (please complete the following information):**

- N/A

**Additional context**

- None
