### ISSUE TITLE
An option to use the Sonarr V3 image should be given (and perhaps defaulted)

### ISSUE THREAD

**Issue by Mchar7** [GhostWriters/DockSTARTer#925]
Sonarr V3 is has been out for years now and, while still technically in beta, is much nicer and widely considered to be about as stable as the V2 release.

The differences between the versions are massive and since the V2-to-V3 have configs are not 1:1, the conversion not seamless. I think DockSTARTer should have all new Sonarr images be defaulted to V3 to prevent the inevitable inconvenience of having to switch in the future anyway. The default downloads given on [Sonarr's website]https://sonarr.tv/#download have been V3 for a long time as well.

There should also be a config option to manually specify the desired image because all that would be needed is to switch the Docker image from `linuxserver/sonarr:latest` to `linuxserver/sonarr:preview`.

**Comment by nemchik** [comment]
You can actually run sonarr v3 very easily. The documentation on running custom changes is here https://dockstarter.com/advanced/overrides/

It doesn't outline sonarr v3 specially, but all you need is this for your override file:
```yaml
version: "3.4"  # this must match the version in docker-compose.yml
services:
  sonarr:
    image: linuxserver/sonarr:preview
```
