### ISSUE TITLE
bad PiHole default options in docker-compose.yml

### ISSUE THREAD

**Issue by juan-apa** [GhostWriters/DockSTARTer#939]
# Bug report

**Describe the bug**
When adding the pihole service, the command `docker-compose up` fails, complaining about the port configuration in pihole.

**To Reproduce**

- Add pihole service via `ds` command
- `cd ~/.docker/compose && docker-compose up`

**Expected behavior**
All the services configured should start with no problems

**System**
(please complete the following information):

- OS: Ubuntu
- Version 20.04

**Comment by juan-apa** [comment]
The solution to this is changing the file `compose/.apps/pihole/pihole.ports.yml`
lines 6, 7 and 8. it would look like this:
```
services:
  pihole:
    ports:
      - ${PIHOLE_PORT_443}:443
      - ${PIHOLE_PORT_80}:80
      - ${PIHOLE_PORT_53}:53
      - ${PIHOLE_PORT_53}:53/udp
      - ${PIHOLE_PORT_67}:67/udp
```
when I tried to create a branch to create a PR, I got permission denied, so I'm posting the solution here.
